version: 2
jobs:
  build:
    working_directory: ~/circulate
    docker:
      - image: circleci:ubuntu-14.04-XL-922-9410082
    steps:
      - run: mkdir /tests

      - run: chmod -R 777 /tests/

      - run: git clone https://github.com/labsai/EDDI-integration-tests.git /tests

      - run: docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS

      - run: docker build -t labsai/eddi-integration-tests:b$CIRCLE_BUILD_NUM .
      - run: docker push -t labsai/eddi-integration-tests:b$CIRCLE_BUILD_NUM

      - run: docker build -t labsai/eddi-integration-tests:latest .
      - run: docker push -t labsai/eddi-integration-tests:latest
