version: 2
jobs:
  build:
    docker:
      - image: docker:1.13.1-git
    working_directory: ~/tests
    steps:
      - checkout
      - setup_remote_docker

      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
          docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS

          docker build -t labsai/eddi-integration-tests:b$CIRCLE_BUILD_NUM .
          docker push labsai/eddi-integration-tests:b$CIRCLE_BUILD_NUM

          # docker build -t labsai/eddi-integration-tests:4.1.0 .
          # docker push labsai/eddi-integration-tests:4.1.0

          docker build -t labsai/eddi-integration-tests:latest .
          docker push labsai/eddi-integration-tests:latest
          fi
